M48
; DRILL file {KiCad 7.0.5} date Sun Sep 10 10:55:30 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-10T10:55:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X118.115Y-49.035
X118.115Y-129.035
X198.115Y-49.035
X198.115Y-129.035
T0
M30
